project:
  title: "qproject"
  output-dir: output
  # pre-render: prepare.py

format:
  html:
    toc: true
    number-sections: true
    code-overflow: wrap
    code-tools: false
    embed-resources: true
    # theme: flatly
    # theme: litera
    theme: simplex
