project:
  title: "qproject"
  output-dir: output
  # render: 
  #   - 12_rdd_keyvalue_pairs.qmd
  # type: book
  # pre-render: prepare.py

# book: 
#   title: "Distributed architectures for big data processing and analytics"
#   date: now
#   chapters: 
#     - index.qmd
#     - 00_01_intro.qmd
#     - 02_architectures.qmd
#     - 03b_HDFS_clc.qmd
#     - 03_intro_hadoop.qmd
#     - 04_hadoop_implementation.qmd
#     - 05_mapreduce_patterns_1.qmd
#     - 06_mapreduce_advanced_topics.qmd
#     - 07_mapreduce_patterns_2.qmd
#     - 08_sql_operators_mapreduce.qmd
#     - 10b_spark_submit_execute.qmd
#     - 10_intro_spark.qmd
#     - 11_rdd_based_programming.qmd

format:
  html:
    toc: true
    number-sections: true
    code-overflow: scroll
    code-tools: false
    embed-resources: true
    # theme: flatly
    # theme: litera
    theme: simplex
    code-line-numbers: true
    cap-location: top
    code-block-bg: "#f0f3f5"
    
  # pdf: 
  #   toc: true
  #   toc-depth: 2
  #   number-sections: true
  #   code-line-numbers: true
  #   code-block-bg: "#f0f3f5"
  #   code-block-border-left: "#edd39f"
  #   cap-location: top
  #   include-in-header: 
  #     text: |
  #       \usepackage{lscape}
  #       \newcommand{\blandscape}{\begin{landscape}}
  #       \newcommand{\elandscape}{\end{landscape}}

  # pdf: # using the "compact-pdf" Quarto format, see https://github.com/arcruz0/quarto-compact
  #   toc: true
  #   number-sections: true
  #   # shift-heading-level-by: 2
  #   fig-pos: "H"
  #   fig-cap-location: top
  #   geometry:
  #     - top=1in
  #     - right=.8in
  #     - bottom=1in
  #     - left=.8in
  #   link-citations: yes
  #   linkcolor: blue
  #   code-block-bg: "#f0f3f5"
  #   # code-block-border-left: "#edd39f"
  #   code-line-numbers: true
  #   include-in-header: 
  #     text: |
  #       \usepackage{fancyhdr}
  #       \usepackage{titling}
  #       \pagestyle{fancy}
  #       \fancyhf{}
  #       \renewcommand\maketitle{
  #         \fancyhead[C]{
  #           \thetitle
  #           \ifx \theauthor\empty  \else \ – \theauthor \fi
  #           \ifx \thedate\empty  \else \ – \thedate \ \fi
  #         }
  #       }
  #       \fancyfoot[C]{\thepage}
  #       \usepackage{lscape}
  #       \newcommand{\blandscape}{\begin{landscape}}
  #       \newcommand{\elandscape}{\end{landscape}}